### ISSUE TITLE
Quickstart example presented in the README does not work

### ISSUE THREAD

**Issue by acwoss** [encode/typesystem#124]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

The quickstart example presented in the README does not work.

### To reproduce

```python
import typesystem

class Artist(typesystem.Schema):
    name = typesystem.String(max_length=100)

class Album(typesystem.Schema):
    title = typesystem.String(max_length=100)
    release_date = typesystem.Date()

album = Album.validate({
    "title": "Double Negative",
    "release_date": "2018-09-14"
})

print(album)
# Album(title='Double Negative', release_date=datetime.date(2018, 9, 14), artist=Artist(name='Low'))
```

### Expected behavior

Return would be expected

```
Album(title='Double Negative', release_date=datetime.date(2018, 9, 14), artist=Artist(name='Low'))
```

### Actual behavior

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    album = Album.validate({
TypeError: validate() missing 1 required positional argument: 'value'
```

### Environment

- OS: Any
- Python version: 3.8.2 and 3.10
- Typesystem version: 0.4.1

### Additional context

- https://replit.com/@acwoss/ShockedGrumpyMuse

**Comment by aminalaee** [comment]
I think you're referring to the example provided in the README, right?

If you look at the documentation the Quickstart has the new style which works.
The README is out of date and needs to be updated.

PRs are welcome to fix that according to the docs.
