### ISSUE TITLE
Don't echo values back if `format="password"`

### ISSUE THREAD

**Issue by tomchristie** [encode/typesystem#30]
Just needs a tweak in `Form.render_field` to set `value=""`, and a test case.

**Comment by jhtimmins** [comment]
Is this open for anyone to claim? I'm interested in fixing this.

**Comment by tomchristie** [comment]
Absolutely, yup! The two things you'd need to do here are:

* In `render_field` check if `format="password"` and always forcibly set `value=""` in that case.
* Add a test case for coverage.
