### ISSUE TITLE
better error messages for regular expression validation

### ISSUE THREAD

**Issue by wbolster** [encode/typesystem#42]
string fields can have a `pattern` for validation, and since `re.search()` is used under the hood, the pattern can be either a regular expression as a string or a compiled regular expression (`re.compile(...)` is cached and can have flags).

so far so good, but the error message uses this:

```
        "pattern": "Must match the pattern /{pattern}/.",
```

the `str()` conversion for compiled regexes looks like code:

```
>>> my_regex = re.compile('foo')

>>> f"oops: {my_regex}"
"oops: re.compile('foo')"
```

but the `.pattern` attribute is a string:

```
>>> f"oops: {my_regex.pattern}"
'oops: foo'
```

so, perhaps the error message for regular expressions could be improved. :deciduous_tree:

**Comment by tomchristie** [comment]
Right now the `pattern` attribute is strictly a string...

https://github.com/encode/typesystem/blob/master/typesystem/fields.py#L106

I'd be very happy to:

* Accept a PR that switched that to allowing *either* a string or a regex.
* Added a `pattern_regex` property on the String field, which is used to store the compiled pattern.
* Switch the validation to use the compiled `pattern_regex` to perform the matching.

So I think `__init__` would look something like this...

```python
if pattern is None:
    self.patten is None
    self.pattern_regex is None
elif isinstance(pattern, str):
    self.pattern = pattern
    self.pattern_regex = re.compile(pattern)
elif isinstance(pattern, re.Pattern):
    self.pattern = pattern.pattern
    self.pattern_regex = pattern
```

**Comment by tomchristie** [comment]
Similar to this we'll also want beter support for customizing error messages, so that eg...

```python
# Match valid variable names like 'someFunctionName123'
variable_name = String(
    pattern="^a-zA-Z_[a-zA-Z0-9_]*$",
    errors={"pattern": "Must be a valid variable name"}
)
```

**Comment by wbolster** [comment]
i'll cook a pr. it's gonna be simpler than your suggestions.

**Comment by tomchristie** [comment]
Sure thing 👍
However you implement, you'll want to make sure that the `pattern` attribute *always* gets set to a plain string - we inspect that attribute when generating JSON schema documents.
