### ISSUE TITLE
consider adopting a ‘squash only’ merge policy

### ISSUE THREAD

**Issue by wbolster** [encode/typesystem#48]
you may want to consider a ‘squash only’ setting for this project (repo setting in github). history like this:

![image](https://user-images.githubusercontent.com/748944/54034460-2eb5d580-41b7-11e9-9c50-aa4c6300cd27.png)

is a pain to look at, and not useful at all for debugging (e.g. `git bisect`). all that noise in small commits after a review + the merges make the main changes invisible.

**Comment by wbolster** [comment]
(feel free to ignore/close)

**Comment by tomchristie** [comment]
Will switch the default to “squash and merge” yup.
