### ISSUE TITLE
CSRF token field

### ISSUE THREAD

**Issue by foxmask** [encode/typesystem#55]
would TypeSystem  be able to handle CSRF token so the form could be validated _w/o risk_ ?

**Comment by tomchristie** [comment]
Form rendering handles the fields, but not the surrounding content eg. Submit button, form tags, etc, so... you’d include the CSRF token as part of the surrounding html. (Same as Django)

You’d use middleware for CSRF validation/enforcement (same as Django), and the Schema will disregard any unknown keys by default (Same as Django forms / REST framework serializers).

Short: Yes, but it’s the responsibility of Middleware, plus the developer including the CSRF token in the templates.

Aside: SomeSchema.validate(data, strict=True) will error on extra fields.
