### ISSUE TITLE
Optional field

### ISSUE THREAD

**Issue by kdebowski** [encode/typesystem#56]
Is it possible to mark some field as optional? What I mean:

`property = typesystem.String(max_length=100, optional=True)`

This would mean that `property` field may be ommited, but if present it must be `String` with maximum length equal 100 chars.

**Comment by tomchristie** [comment]
So, fields are required *unless* they have a default value set. (Eg. Similar to arguments on a Python function)

Using default=None or default=“” would make the field optional, and indicate what value should be used when it is missing. (Also, allow_blank and allow_null will set a corresponding default, too)

See first section of https://www.encode.io/typesystem/fields/

**Comment by thebigmunch** [comment]
So, typesystem doesn't really support true optional fields. This is a problem with the data I'm working with (Google Music). There are plenty of fields that may simply not exist and should not have any default value. Some of these include YouTube video references, album art links, attributions, rating, last rating timestamp, and more. Every other schema library I've used before supported true optional fields. This is a deal-breaker as far as my current use case and at least one potential use case is concerned.
