### ISSUE TITLE
Added feedstock to conda-forge

### ISSUE THREAD

**Issue by k-dominik** [encode/typesystem#61]
Dear @tomchristie,

I'm in the process of adding a feedstock for `typesystem` to conda-forge: https://github.com/conda-forge/staged-recipes/pull/8008 in order to be able to have the latest versions of `apistar` available there as well.

Please let me know if that's okay with you :) and thank you very much for those awesome packages!

**Comment by tomchristie** [comment]
So long as you're following [the license terms](https://github.com/encode/typesystem/blob/master/LICENSE.md) you're welcome.

**Comment by k-dominik** [comment]
absolutely, thank you very much, again!
