### ISSUE TITLE
UUID field

### ISSUE THREAD

**Issue by thomasjiangcy** [encode/typesystem#62]
What do you think about supporting UUIDs? I guess they are somewhat common when dealing with database objects.

`String` field could be extended to support it and the eventual API could be:

```python
typesystem.String(format="uuid")
```

**Comment by tomchristie** [comment]
Would be happy to do so yup.
Look to the date/time implementations for guidance if you consider a pull request for this.
Closing this since I don’t see it as a pressing requirement, but very happy to accept pull requests towards it.
