### ISSUE TITLE
ValidationError can't be shown with `traceback.print_exc()` in Python 3.6

### ISSUE THREAD

**Issue by florimondmanca** [encode/typesystem#64]
Consider the following code:

```python
import traceback
import typesystem

try:
    typesystem.Integer().validate("hello")
except typesystem.ValidationError:
    traceback.print_exc()
```

Because of an issue with Python 3.6 discussed in [issue 28803](https://bugs.python.org/issue28603), since `ValidationError` implements `__eq__` but not `__hash__` it is not hashable and `print_exc()` fails to process it correctly.

```
TypeError: unhashable type: 'ValidationError'
```

(Full traceback available [here](https://travis-ci.org/bocadilloproject/bocadillo/jobs/513086149))

Looks like we'd need to implement `ValidationError.__hash__()` to fix this.

**Comment by tomchristie** [comment]
Okay no problem. A failing test case and something like `ident = (self.code, tuple(self.key)); return hash(ident)` ought to do the trick.

(Ie a hash of its position in the document and the error code)
