### ISSUE TITLE
Script to autogenerate .pyi stub files for typesystem schema classes

### ISSUE THREAD

**Issue by skewty** [encode/typesystem#66]
Autocompletion / intellisense is a nice-to-have feature.  Currently neither **PyCharm** nor **VScode** offer any autocompletion for **typesystem** schema classes.  This may lessen the likelihood of its usage and adoption.

It would be nice if a script was included with **typesystem** that could be configured to be called automatically on file save and that auto-generates/updates a .pyi stub file for classes subclassing `typesystem.Schema`.

Auto-generated stub code could be surrounded by special markers in python comments that serve double duty.
1. warn developers that modification within could be overwritten without warning
2. simple start / end line number identification (don't overwrite user additions to .pyi files)

Including typesystem schema classes along with other code would result in .pyi files that didn't  include stubs for the other code.  Some possible options:
1. don't mix your typesystem schemas with other code
2. manually write stubs for the other code
3. use [mypy stub generator](https://github.com/python/mypy)
4. use [make-stub-files](https://github.com/edreamleo/make-stub-files)

What do you think?  Comments?

**Comment by tomchristie** [comment]
I don't think it'd be very practical.
Neither Django or SQLAlchemy models offer anything along these lines, and I don't think we should either.

**Comment by skewty** [comment]
In PyCharm, at least, there is built-in support for:
* Django models
* SQLAlchemy models
* @dataclass classes
* @attr.s classes

The chance of JetBrains picking up support for typeshed is low given its current popularity and comparing typeshed against arguably the two biggest heavyweights in the Python world is perhaps premature.

That said, you are 100% correct and your point stands without contest.  
Thanks for the reply with reason and thank you for all the great work and tools you have been putting out there for everyone.
