### ISSUE TITLE
Opportunity to avoid double lookups in Schema.__getitem__

### ISSUE THREAD

**Issue by skewty** [encode/typesystem#73]
https://github.com/encode/typesystem/blob/7e8f1a858b0a08f6373d1df18202dc38593cbcd5/typesystem/schemas.py#L175

It seems to me that the dictionary key and attribute lookups occur twice.  I believe the following code will not have any side effects and avoids the double lookups.

```python
    def __getitem__(self, key: typing.Any) -> typing.Any:
        try:
            field = self.fields[key]
            value = getattr(self, key)
        except (KeyError, AttributeError):
            raise KeyError(key) from None
        else:
            return field.serialize(value)
```

Overall, the code looks great!  (I love type hinting in conjunction with PEP8)

Is there any reason you don't use `is` for Boolean comparison?  You seem so precise and strict elsewhere in your code that this seems to be a bit of an outlier (to me).

Thanks for your efforts!  I am looking forward to putting Starlette and Typesystem through some testing and perhaps using it for our project at work (replacing both Django + Channels and Flask + Websockets in our existing code base).

**Comment by tomchristie** [comment]
I like your proposed change here yup - wanna raise a pull request for it?

> Is there any reason you don't use is for Boolean comparison? You seem so precise and strict elsewhere in your code that this seems to be a bit of an outlier (to me).

Not sure exactly where you mean re. bools but happy to take suggestions there too.

**Comment by skewty** [comment]
Regarding the `bool` comparisons:

[From PEP8 Guide](https://pep8.org/#programming-recommendations)

> Comparisons to singletons like None should always be done with is or is not, never the equality operators.

`True` and `False` are singletons.

```python
x = True
if x:
    print('X')
```

The above is non-pythonic PEP8.  Below is more pythonic and PEP8 compliant:

```python
x = True
if x is True:
    print('X')
```

This is an excessively simple case, of course.  But in most code the desire is not always clear.
```python
x = ''
if x:
    print('X')
```
What is desired here?  Did they really want a `len(x) > 0` or a `x is not None`?  In an effort to always be precise and clear, the `is` operator is to be used instead of relying on the implied Truthy / Falsey nature of the statement.

**Comment by tomchristie** [comment]
Not super convinced about the value of using `is` wrt. boolean comparisons. Happy to *consider* any PRs there, but let's treat that as a seperate issue if so.
