### ISSUE TITLE
Support dataclasses?

### ISSUE THREAD

**Issue by shamrin** [encode/typesystem#76]
@tomchristie Are you open to support `@dataclass`-decorated classes in `typesystem`? Similar to what `attrs` project is [doing with `@attr.s(auto_attribs=True)`][1]. I'd like to try contributing the support, but wanted to check if it's within the scope of the project.

[1]: https://www.attrs.org/en/stable/types.html

Here is how some of the examples from `typesystem` documentation could be rewritten, if dataclasses were supported:

```python
from dataclasses import dataclass
from datetime import date
from typesystem import field, validate

# Example from README.md

@dataclass
class Artist:
    name: str = field(max_length=100)

@dataclass
class Album:
    title: str = field(max_length=100)
    release_date: date
    artist: Artist

validate(Album, {
    "title": "Double Negative",
    "release_date": "2018-09-14",
    "artist": {"name": "Low"}
})

# Example from documentation

@dataclass
class Organisation:
    name: str = field(title="Name", max_length=100)
    date_created: date = field(title="Date created", default=datetime.date.today)
    owner: User = field(allow_null=True)
```

`typesystem.field` could be a thin wrapper around around [`dataclasses.field`][2], using `metadata` argument. For example, `Artist` and `Organisation` above are the same as this:

[2]: https://docs.python.org/3/library/dataclasses.html#dataclasses.field

```python
@dataclass
class User:
    name: str = dataclasses.field(metadata={'typesystem': {'max_length': 100}})

@dataclass
class Organisation:
    name: str = dataclasses.field(
        metadata={'typesystem': {'title': 'Name', 'max_length': 100}},
    )
    date_created: date = dataclasses.field(
       default_factory=datetime.date,
       metadata={'typesystem': {'title': 'Date created'}},
    )
    owner: User = dataclasses.field(
        metadata={'typesystem': {'allow_null': True}},
    )
```

**Comment by tomchristie** [comment]
Good question. At this point in time it'd be a no.
I've got too many other wheels spinning to want to expand the design scope of typesystem in that direction. :)
