### ISSUE TITLE
How to use deserialized JSON Schema with Forms?

### ISSUE THREAD

**Issue by john251** [encode/typesystem#80]
I haven't found this to be documented. Initially I assumed that deserialized JSON Schema is equivalent to the coded one, but it seems not.

I cannot use result of ```typesystem.from_json_schema(schema)``` to call ```forms.Form()``` as from_json_schema returns only a validator, not the Schema class.

**Comment by tomchristie** [comment]
You can't do that, nope.

There's all kinds of validators that `from_json_schema` might return that can't be represented as a forms.

Schemas are a particular subset of `typesystem.Object` that have a fixed set of fields, which means that we know we can treat them like objects, and also means that we can render them to forms, as they'll have a fixed set of key/value pairs to represent as form inputs.
