### ISSUE TITLE
IntegerField allows string

### ISSUE THREAD

**Issue by aaronlelevier** [encode/typesystem#94]
# Summary

I ran into the following scenario. A string will pass validation for an `Integer` if it can be coerced to an integer. It seems like validation should fail here. Especially if the range is being asserted of the Integer, on top of its type.

Could this possibly change to fail validation if a string is passed here?

Current output:

```
>>> import typesystem
>>> field = typesystem.Integer(minimum=0, maximum=10)
>>> field.validate('5')
5
>>> field.validate(5)
5
```

# Version

Python 3.7

Typesystem 0.2.4

**Comment by aminalaee** [comment]
This is an expected behaviour.
